services:
  docs:
    build: .
    container_name: docs

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - docs
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    restart: always
